
import type { Product, Category, Testimonial } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Watches', slug: 'watches' },
  { id: '2', name: 'Bags', slug: 'bags' },
  { id: '3', name: 'Jewelry', slug: 'jewelry' },
  { id: '4', name: 'Sunglasses', slug: 'sunglasses' },
  { id: '5', name: 'New Arrivals', slug: 'new-arrivals' },
  { id: '6', name: 'Best Sellers', slug: 'best-sellers' },
  { id: '7', name: 'Sale', slug: 'sale' },
];

// Product data is now managed in Firestore.
// This file can be used for other static data like categories or testimonials.
export const products: Omit<Product, 'id'>[] = [
  {
    name: 'ChronoGold Watch',
    shortDescription: 'Elegant gold chronograph.',
    description: 'A masterpiece of timekeeping, this watch combines classic design with modern precision. The gold-plated stainless steel case and sophisticated dial make it a statement piece for any occasion.',
    price: 45000,
    discountedPrice: 39900,
    category: 'watches',
    imageUrls: [],
    stock: 15,
    rating: 4.8,
    reviews: [],
    isNewArrival: true,
    isBestSeller: false,
    onSale: true,
  },
  {
    name: 'Classic Timekeeper',
    shortDescription: 'A timeless silver watch.',
    description: 'Featuring a sleek silver finish and a minimalist black dial, this watch is the epitome of understated elegance. Perfect for both formal events and everyday wear.',
    price: 25000,
    discountedPrice: null,
    category: 'watches',
    imageUrls: [],
    stock: 25,
    rating: 4.6,
    reviews: [],
    isNewArrival: false,
    isBestSeller: true,
    onSale: false,
  },
  {
    name: 'Arabian Black Aura Watch',
    shortDescription: 'A mysterious and alluring timepiece with Arabic numerals.',
    description: 'Embrace the mystique of the desert night with the Arabian Black Aura watch. This stunning timepiece features a matte black finish and a deep black dial adorned with elegant Eastern Arabic numerals. Subtle golden accents recall distant stars, and the comfortable black silicone strap ensures all-day wearability. It\'s a watch that doesn\'t just tell time, but tells a story of heritage and mystery.',
    price: 1300,
    discountedPrice: null,
    category: 'watches',
    imageUrls: ['https://storage.googleapis.com/stedi-dev-public-model-outputs/arabian-black-aura-watch.jpg'],
    stock: 20,
    rating: 4.7,
    reviews: [],
    isNewArrival: true,
    isBestSeller: false,
    onSale: false,
  },
  {
    name: 'Jet-Setter Leather Bag',
    shortDescription: 'Spacious and stylish leather travel bag.',
    description: 'Crafted from full-grain leather, this bag is designed for the modern traveler. With multiple compartments and a durable design, it\'s the perfect companion for your weekend getaways or business trips.',
    price: 32000,
    discountedPrice: null,
    category: 'bags',
    imageUrls: [],
    stock: 10,
    rating: 4.9,
    reviews: [],
    isNewArrival: false,
    isBestSeller: true,
    onSale: false,
  },
  {
    name: 'Emerald Drop Earrings',
    shortDescription: 'Exquisite emerald and diamond earrings.',
    description: 'These breathtaking earrings feature stunning pear-shaped emeralds, surrounded by a halo of brilliant-cut diamonds. Set in 18k white gold, they are a true testament to luxury and fine jewelry making.',
    price: 150000,
    discountedPrice: 125000,
    category: 'jewelry',
    imageUrls: [],
    stock: 5,
    rating: 4.9,
    reviews: [],
    isNewArrival: false,
    isBestSeller: false,
    onSale: true,
  },
  {
    name: 'Aviator Pro Sunglasses',
    shortDescription: 'Classic aviators with polarized lenses.',
    description: 'Protect your eyes in style with these classic aviator sunglasses. Featuring a lightweight metal frame and polarized lenses, they offer 100% UV protection and reduce glare for crystal clear vision.',
    price: 12000,
    discountedPrice: null,
    category: 'sunglasses',
    imageUrls: [],
    stock: 30,
    rating: 4.7,
    reviews: [],
    isNewArrival: false,
    isBestSeller: true,
    onSale: false,
  },
   {
    name: 'The Minimalist Tote',
    shortDescription: 'A chic and simple everyday tote bag.',
    description: 'Designed for the modern woman on the go, this tote combines functionality with minimalist aesthetics. Made from high-quality vegan leather, it\'s spacious enough to carry all your essentials.',
    price: 18000,
    discountedPrice: null,
    category: 'bags',
    imageUrls: [],
    stock: 20,
    rating: 4.5,
    reviews: [],
    isNewArrival: true,
    isBestSeller: false,
    onSale: false,
  },
];
