import type { Product, Category, Testimonial } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Watches', slug: 'watches' },
  { id: '2', name: 'Bags', slug: 'bags' },
  { id: '3', name: 'Jewelry', slug: 'jewelry' },
  { id: '4', name: 'Sunglasses', slug: 'sunglasses' },
  { id: '5', name: 'New Arrivals', slug: 'new-arrivals' },
  { id: '6', name: 'Best Sellers', slug: 'best-sellers' },
  { id: '7', name: 'Sale', slug: 'sale' },
];

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'ChronoGold Watch',
    shortDescription: 'Elegant gold chronograph.',
    description: 'A masterpiece of timekeeping, the ChronoGold Watch features a stunning gold-plated stainless steel case, a detailed chronograph dial, and a supple leather strap. Water-resistant up to 50 meters.',
    price: 450,
    category: 'watches',
    imageIds: ['watch-2', 'watch-4'],
    stock: 15,
    rating: 4.8,
    reviews: [],
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: 'prod_002',
    name: 'Silver Timepiece',
    shortDescription: 'Classic silver wristwatch.',
    description: 'Embrace timeless elegance with this classic silver timepiece. Its clean dial, polished stainless steel case, and comfortable mesh strap make it a versatile accessory for any occasion.',
    price: 280,
    category: 'watches',
    imageIds: ['watch-1', 'watch-3'],
    stock: 25,
    rating: 4.6,
    reviews: [],
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: 'prod_003',
    name: 'The Executive Bag',
    shortDescription: 'Premium leather handbag.',
    description: 'Crafted from the finest full-grain leather, The Executive Bag is designed for the modern professional. It features multiple compartments, a padded laptop sleeve, and a detachable shoulder strap.',
    price: 320,
    category: 'bags',
    imageIds: ['bag-1', 'bag-3'],
    stock: 20,
    rating: 4.9,
    reviews: [],
    isNewArrival: true,
    isBestSeller: true,
  },
  {
    id: 'prod_004',
    name: 'Urban Tote',
    shortDescription: 'Stylish and spacious canvas tote.',
    description: 'The Urban Tote is your perfect companion for city adventures. Made from durable canvas with leather accents, it offers ample space for all your essentials.',
    price: 150,
    category: 'bags',
    imageIds: ['bag-2', 'bag-4'],
    stock: 30,
    rating: 4.5,
    reviews: [],
    isNewArrival: false,
    isBestSeller: false,
  },
  {
    id: 'prod_005',
    name: 'Solitaire Sparkle Ring',
    shortDescription: 'Exquisite diamond ring.',
    description: 'A stunning solitaire diamond set in a 14k gold band. The Solitaire Sparkle Ring is a timeless symbol of love and commitment, crafted to perfection.',
    price: 1200,
    discountedPrice: 999,
    category: 'jewelry',
    imageIds: ['ring-1'],
    stock: 10,
    rating: 5.0,
    reviews: [],
    isNewArrival: false,
    isBestSeller: true,
    onSale: true,
  },
    {
    id: 'prod_006',
    name: 'Golden Link Bracelet',
    shortDescription: 'Bold gold chain bracelet.',
    description: 'Make a statement with this bold gold link bracelet. Each link is meticulously crafted and polished to a high shine, creating a look of effortless luxury.',
    price: 250,
    category: 'jewelry',
    imageIds: ['bracelet-1'],
    stock: 18,
    rating: 4.7,
    reviews: [],
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    id: 'prod_007',
    name: 'Aviator Shades',
    shortDescription: 'Classic aviator sunglasses.',
    description: 'The iconic aviator style, updated with modern materials. These sunglasses feature lightweight metal frames, polarized lenses, and offer 100% UV protection.',
    price: 180,
    category: 'sunglasses',
    imageIds: ['sunglasses-1', 'sunglasses-2'],
    stock: 40,
    rating: 4.8,
    reviews: [],
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    id: 'prod_008',
    name: 'Retro Round Glasses',
    shortDescription: 'Vintage-inspired round frames.',
    description: 'Channel a retro vibe with these stylish round sunglasses. The unique frame design and gradient lenses make them a standout accessory.',
    price: 160,
    discountedPrice: 120,
    category: 'sunglasses',
    imageIds: ['sunglasses-3', 'sunglasses-4'],
    stock: 35,
    rating: 4.6,
    reviews: [],
    isNewArrival: false,
    isBestSeller: false,
    onSale: true,
  },
];

export const testimonials: Testimonial[] = [
    {
        id: 'test_1',
        name: 'Jessica L.',
        location: 'New York, USA',
        quote: 'The quality of the watch I bought is exceptional. It looks even more stunning in person. Fast shipping and beautiful packaging!',
        avatarId: 'testimonial-1-avatar'
    },
    {
        id: 'test_2',
        name: 'David R.',
        location: 'London, UK',
        quote: 'I purchased The Executive Bag and it has exceeded all my expectations. It\'s the perfect blend of style and functionality. Highly recommend!',
        avatarId: 'testimonial-2-avatar'
    },
    {
        id: 'test_3',
        name: 'Priya S.',
        location: 'Mumbai, India',
        quote: 'Talha Luxe is my go-to for accessories. The designs are unique and the customer service is top-notch. I always get compliments on my jewelry.',
        avatarId: 'testimonial-3-avatar'
    }
];
