
import type { Product, Category, Testimonial } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Watches', slug: 'watches' },
  { id: '2', name: 'Bags', slug: 'bags' },
  { id: '3', name: 'Jewelry', slug: 'jewelry' },
  { id: '4', name: 'Sunglasses', slug: 'sunglasses' },
  { id: '5', name: 'New Arrivals', slug: 'new-arrivals' },
  { id: '6', name: 'Best Sellers', slug: 'best-sellers' },
  { id: '7', name: 'Sale', slug: 'sale' },
];

// Product data is now managed in Firestore.
// This file can be used for other static data like categories or testimonials.
export const products: Omit<Product, 'id'>[] = [
  {
    name: 'ChronoGold Watch',
    shortDescription: 'Elegant gold chronograph.',
    description: 'A masterpiece of timekeeping, this watch combines classic design with modern precision. The gold-plated stainless steel case and sophisticated dial make it a statement piece for any occasion.',
    price: 450,
    discountedPrice: 399,
    category: 'watches',
    imageUrls: ['https://picsum.photos/seed/watch-2/600/600', 'https://picsum.photos/seed/watch-4/600/600'],
    stock: 15,
    rating: 4.8,
    reviews: [],
    isNewArrival: true,
    isBestSeller: false,
    onSale: true,
  },
  {
    name: 'Classic Timekeeper',
    shortDescription: 'A timeless silver watch.',
    description: 'Featuring a sleek silver finish and a minimalist black dial, this watch is the epitome of understated elegance. Perfect for both formal events and everyday wear.',
    price: 250,
    category: 'watches',
    imageUrls: ['https://picsum.photos/seed/watch-1/600/600', 'https://picsum.photos/seed/watch-3/600/600'],
    stock: 25,
    rating: 4.6,
    reviews: [],
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    name: 'The Executive Bag',
    shortDescription: 'Premium leather briefcase.',
    description: 'Crafted from full-grain leather, this briefcase is designed for the modern professional. It features multiple compartments for your laptop and documents, ensuring you stay organized and stylish.',
    price: 350,
    category: 'bags',
    imageUrls: ['https://picsum.photos/seed/bag-3/600/600', 'https://picsum.photos/seed/bag-1/600/600'],
    stock: 10,
    rating: 4.9,
    reviews: [],
    isNewArrival: true,
    isBestSeller: false,
  },
  {
    name: 'Everyday Tote',
    shortDescription: 'Versatile canvas tote.',
    description: 'This spacious canvas tote is your perfect companion for daily errands, trips to the market, or a casual day out. Durable, stylish, and practical.',
    price: 75,
    category: 'bags',
    imageUrls: ['https://picsum.photos/seed/bag-2/600/600'],
    stock: 50,
    rating: 4.5,
    reviews: [],
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    name: 'Diamond Solitaire Ring',
    shortDescription: 'Exquisite diamond ring.',
    description: 'A breathtaking solitaire diamond set in a platinum band. This ring is a timeless symbol of love and commitment, crafted to perfection.',
    price: 1200,
    category: 'jewelry',
    imageUrls: ['https://picsum.photos/seed/ring-1/600/600'],
    stock: 8,
    rating: 4.9,
    reviews: [],
    isNewArrival: false,
    isBestSeller: false,
  },
  {
    name: 'Silver Serenity Necklace',
    shortDescription: 'Delicate silver necklace.',
    description: 'A simple yet elegant silver chain necklace that adds a touch of sophistication to any outfit. Made from sterling silver, it is perfect for layering or wearing on its own.',
    price: 95,
    category: 'jewelry',
    imageUrls: ['https://picsum.photos/seed/chain-1/600/600'],
    stock: 30,
    rating: 4.7,
    reviews: [],
    isNewArrival: true,
    isBestSeller: true,
  },
   {
    name: 'Gilded Link Bracelet',
    shortDescription: 'Bold gold chain bracelet.',
    description: 'Make a statement with this chunky gold link bracelet. It\'s a bold accessory that exudes confidence and style, perfect for elevating any look.',
    price: 180,
    category: 'jewelry',
    imageUrls: ['https://picsum.photos/seed/bracelet-1/600/600'],
    stock: 20,
    rating: 4.6,
    reviews: [],
    isNewArrival: false,
    isBestSeller: false,
  },
  {
    name: 'Aviator Shades',
    shortDescription: 'Classic aviator sunglasses.',
    description: 'Iconic and always in style, these aviator sunglasses feature a lightweight metal frame and polarized lenses for maximum protection and clarity.',
    price: 150,
    category: 'sunglasses',
    imageUrls: ['https://picsum.photos/seed/sunglasses-1/600/600'],
    stock: 40,
    rating: 4.8,
    reviews: [],
    isNewArrival: false,
    isBestSeller: true,
  },
  {
    name: 'Wayfarer Classics',
    shortDescription: 'Timeless wayfarer sunglasses.',
    description: 'The classic wayfarer design gets a modern update with high-quality acetate frames and scratch-resistant lenses. A must-have accessory for any season.',
    price: 130,
    category: 'sunglasses',
    imageUrls: ['https://picsum.photos/seed/sunglasses-2/600/600'],
    stock: 35,
    rating: 4.7,
    reviews: [],
    isNewArrival: false,
    isBestSeller: false,
  },
  {
    name: 'Round Retro Specs',
    shortDescription: 'Vintage-inspired round shades.',
    description: 'Channel a retro vibe with these stylish round sunglasses. The unique design and quality construction make them a standout accessory.',
    price: 140,
    discountedPrice: 110,
    category: 'sunglasses',
    imageUrls: ['https://picsum.photos/seed/sunglasses-3/600/600'],
    stock: 28,
    rating: 4.5,
    reviews: [],
    isNewArrival: true,
    isBestSeller: false,
    onSale: true,
  }
];


export const testimonials: Testimonial[] = [
    {
        id: 'test_1',
        name: 'Jessica L.',
        location: 'New York, USA',
        quote: 'The quality of the watch I bought is exceptional. It looks even more stunning in person. Fast shipping and beautiful packaging!',
        avatarId: 'testimonial-1-avatar'
    },
    {
        id: 'test_2',
        name: 'David R.',
        location: 'London, UK',
        quote: 'I purchased The Executive Bag and it has exceeded all my expectations. It\'s the perfect blend of style and functionality. Highly recommend!',
        avatarId: 'testimonial-2-avatar'
    },
    {
        id: 'test_3',
        name: 'Priya S.',
        location: 'Mumbai, India',
        quote: 'Talha Luxe is my go-to for accessories. The designs are unique and the customer service is top-notch. I always get compliments on my jewelry.',
        avatarId: 'testimonial-3-avatar'
    }
];
